begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
insert into auth.users(id,instance_id,aud,role,created_at,updated_at) values
 ('77777777-7777-4777-8777-777777777777','00000000-0000-0000-0000-000000000000','authenticated','authenticated',now(),now());
set local role authenticated;
select set_config('request.jwt.claim.sub','77777777-7777-4777-8777-777777777777',true);
select public.create_trip('Logistics regression','undecided','{}',null,null,'77777777-aaaa-4aaa-8aaa-aaaaaaaaaaaa');
create temporary table logistics_trip as select id from public.trips where name='Logistics regression';
create function pg_temp.room() returns jsonb language sql as $$select public.get_trip_quest((select id from logistics_trip))$$;
create function pg_temp.act(action jsonb, key uuid default extensions.gen_random_uuid()) returns jsonb language sql as $$select public.update_trip_quest((select id from logistics_trip),action,key)$$;
reset role;
update public.trips set planning_started_at=now() where id=(select id from logistics_trip);
set local role authenticated;
select pg_temp.room();
reset role;
update public.trip_quests set stage='budget',budget_resume_stage='logistics',period='{"startsOn":"2027-10-12","endsOn":"2027-10-16","label":"Trip","reason":"Shared"}',selected_country_code='JP',attraction_ids=array['jp-sensoji'] where trip_id=(select id from logistics_trip);
update public.trip_quest_inputs set comfortable_budget_myr=3000,max_budget_myr=3000 where trip_id=(select id from logistics_trip);
set local role authenticated;
select is(pg_temp.act('{"type":"finish"}')->>'stage','logistics','Legacy Budget resumes Logistics');
select lives_ok($$select pg_temp.act('{"type":"transport","transport":{"direction":"arrival","mode":"flight","departureLocation":"KUL","arrivalLocation":"NRT","departureAt":"2027-10-12T07:00:00+08:00","arrivalAt":"2027-10-12T14:30:00+09:00","cost":850,"bookingLink":null,"status":"selected"}}')$$,'save a selected inbound journey');
select is(jsonb_array_length(pg_temp.room()->'logistics'->'transport'),1,'transport persists in the shared room');
select lives_ok($$select pg_temp.act('{"type":"stay","stay":{"id":"88888888-8888-4888-8888-888888888888","name":"Crew stay","area":"Tokyo","image":"https://example.com/hotel.jpg","latitude":35.7,"longitude":139.7,"totalCost":1050,"checkIn":"2027-10-12","checkOut":"2027-10-16","rating":8.4,"distance":"6 min from station","bookingLink":"https://example.com/book","provider":"Provider"}}')$$,'stay options persist');
select pg_temp.act('{"type":"stay_vote","stayId":"88888888-8888-4888-8888-888888888888"}');
select pg_temp.act('{"type":"stay_vote","stayId":"88888888-8888-4888-8888-888888888888"}');
select is(jsonb_array_length(pg_temp.room()->'logistics'->'votes'),1,'repeat votes do not inflate the count');
select pg_temp.act('{"type":"confirm_stay","stayId":"88888888-8888-4888-8888-888888888888"}');
select is(pg_temp.room()->'logistics'->>'selectedStayId','88888888-8888-4888-8888-888888888888','one stay is confirmed');
select throws_ok($$select pg_temp.act('{"type":"complete_logistics","skip":true,"revision":0}')$$,'P0001','The logistics summary changed. Review the latest summary before confirming.','stale summaries cannot be confirmed');
select throws_ok($$select pg_temp.act(jsonb_build_object('type','complete_logistics','skip',false,'revision',(pg_temp.room()->>'revision')::integer))$$,'P0001','Confirm travel and a stay, or generate a draft for now.','missing return travel requires draft acknowledgement');
select is(pg_temp.act(jsonb_build_object('type','complete_logistics','skip',true,'revision',(pg_temp.room()->>'revision')::integer))->>'stage','complete','unknown logistics never block a draft');
select is(pg_temp.act('{"type":"edit_logistics"}')->>'stage','logistics','the organiser can revisit Logistics');
select pg_temp.act('{"type":"skip_stay"}');
select is(pg_temp.room()->'logistics'->'selectedStayId','null'::jsonb,'choosing later clears the stay constraint');
select ok(not has_function_privilege('authenticated','private.validate_logistics_option(jsonb,text)','execute'),'clients cannot invoke internal validation helpers');
select pg_temp.act(jsonb_build_object('type','complete_logistics','skip',true,'revision',(pg_temp.room()->>'revision')::integer));
select is(pg_temp.act('{"type":"skip_transport"}')->>'stage','logistics','transport input remains available after draft completion');
select pg_temp.act(jsonb_build_object('type','complete_logistics','skip',true,'revision',(pg_temp.room()->>'revision')::integer));
select is(pg_temp.act('{"type":"stay_vote","stayId":"88888888-8888-4888-8888-888888888888"}')->>'stage','logistics','stay voting remains available after draft completion');
select * from finish();
rollback;
