begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
insert into auth.users(id) values ('33333333-aaaa-4aaa-8aaa-aaaaaaaaaaaa'),('33333333-bbbb-4bbb-8bbb-bbbbbbbbbbbb');
set local role authenticated;
select set_config('request.jwt.claim.sub','33333333-aaaa-4aaa-8aaa-aaaaaaaaaaaa',true);
select lives_ok($$select public.save_inspiration('https://www.instagram.com/p/test/','Japan','Kyoto market')$$,'save without a trip');
select lives_ok($$select public.save_inspiration('https://www.instagram.com/p/test/','Food','Kyoto market')$$,'move existing link');
select is((select count(*)::integer from public.saved_inspiration),1,'deduplicates saved URL');
select is((select folder from public.saved_inspiration),'Food','folder persists');
select throws_ok($$update public.saved_inspiration set status='ready'$$,'42501',null,'client cannot forge analysis');
select set_config('request.jwt.claim.sub','33333333-bbbb-4bbb-8bbb-bbbbbbbbbbbb',true);
select is((select count(*)::integer from public.saved_inspiration),0,'other users cannot read saved content');
delete from public.saved_inspiration;
select set_config('request.jwt.claim.sub','33333333-aaaa-4aaa-8aaa-aaaaaaaaaaaa',true);
select is((select count(*)::integer from public.saved_inspiration),1,'other users cannot delete saved content');
reset role;
update public.saved_inspiration set status='ready',analysis='{"title":"Old"}',lease=extensions.gen_random_uuid() where user_id='33333333-aaaa-4aaa-8aaa-aaaaaaaaaaaa';
set local role authenticated;
select public.save_inspiration('https://www.instagram.com/p/test/','Food','New caption');
select is((select status from public.saved_inspiration),'saved','changed caption invalidates analysis');
select ok((select analysis is null and lease is null from public.saved_inspiration),'stale worker cannot overwrite edited caption');
delete from public.saved_inspiration;
select is((select count(*)::integer from public.saved_inspiration),0,'owner can remove link');
select * from finish();
rollback;
